Repository ChatCode9/ChatCode-backend, pull requests merged in 2024-06, with the labels that each got.

#43 Feature/#4 oauth2 jwt
  src/main/java/com/chatcode/config/SecurityConfig.java
  src/main/java/com/chatcode/config/auth/LoginUser.java
  src/main/java/com/chatcode/config/auth/enums/Status.java
  src/main/java/com/chatcode/config/auth/enums/StatusConverter.java
  src/main/java/com/chatcode/config/auth/oauth/OAuth2LoginFilter.java
  src/main/java/com/chatcode/config/auth/oauth/OAuth2LoginUserService.java
  src/main/java/com/chatcode/config/auth/oauth/OAuth2SuccessHandler.java
  src/main/java/com/chatcode/config/auth/oauth/util/HttpUtils.java
  src/main/java/com/chatcode/controller/AvatarController.java
  src/main/java/com/chatcode/controller/CategoryController.java
  src/main/java/com/chatcode/controller/FollowController.java
  src/main/java/com/chatcode/controller/ScrapController.java
  src/main/java/com/chatcode/domain/entity/User.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
Labels: ⭐ Feature

#49 Feature/#33 refactor article opinion
  src/main/java/com/chatcode/controller/ArticleController.java
  src/main/java/com/chatcode/domain/article/CategoryType.java
  src/main/java/com/chatcode/domain/article/SortType.java
  src/main/java/com/chatcode/domain/article/StatusType.java
  src/main/java/com/chatcode/domain/common/PageInfo.java
  src/main/java/com/chatcode/domain/common/type/BaseEnum.java
  src/main/java/com/chatcode/domain/entity/Article.java
  src/main/java/com/chatcode/dto/ArticleResponseDTO.java
  src/main/java/com/chatcode/dto/article/ArticleRequestDTO.java
  src/main/java/com/chatcode/dto/article/ArticleResponseDTO.java
  src/main/java/com/chatcode/dto/article/ArticleRetrieveRequest.java
  src/main/java/com/chatcode/dto/article/ArticleRetrieveServiceDto.java
  src/main/java/com/chatcode/dto/common/PageRequest.java
  src/main/java/com/chatcode/repository/ArticleRepository.java
  src/main/java/com/chatcode/repository/article/ArticleReadRepository.java
  src/main/java/com/chatcode/service/ArticleService.java
  src/main/resources/yaml/application-log.yaml
Labels: ⭐ Feature

#52 Fix/#41 avatar tag
  db/mysql/initdb.d/create_table.sql
  src/main/java/com/chatcode/controller/InterestTagController.java
  src/main/java/com/chatcode/domain/entity/InterestTag.java
  src/main/java/com/chatcode/repository/tag/InterestTagReadRepository.java
  src/main/java/com/chatcode/service/InterestTagService.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/Keys.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/InterestTag.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/User.java
Labels: 🐞 Bug

#50 Refactor/#47 authorization test
  src/main/java/com/chatcode/config/SecurityConfig.java
  src/main/java/com/chatcode/config/auth/LoginUser.java
  src/main/java/com/chatcode/config/auth/LoginUserService.java
  src/main/java/com/chatcode/config/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/chatcode/config/auth/jwt/LoginUserAuthentication.java
  src/main/java/com/chatcode/config/auth/oauth/OAuth2LoginUserService.java
  src/main/java/com/chatcode/config/auth/oauth/dto/LoginRequest.java
  src/main/java/com/chatcode/config/dummy/DummyDevInit.java
  src/main/java/com/chatcode/config/dummy/DummyObject.java
  src/main/resources/yaml/application-jwt.yaml
Labels: 🛠️ Refactor

#54 refactor(interestTag): DELETE method request body 삭제
  src/main/java/com/chatcode/controller/InterestTagController.java
  src/main/java/com/chatcode/service/AvatarService.java
  src/main/java/com/chatcode/service/InterestTagService.java
Labels: 🛠️ Refactor

#53 Feature/add article dummy
  build.gradle
  db/mysql/initdb.d/create_table.sql
  src/main/java/com/chatcode/config/dummy/DummyDevInit.java
  src/main/java/com/chatcode/config/dummy/DummyObject.java
  src/main/java/com/chatcode/domain/entity/Article.java
  src/main/java/com/chatcode/domain/entity/Content.java
  src/main/java/com/chatcode/domain/entity/Opinion.java
  src/main/java/com/chatcode/dto/article/ArticleResponseDTO.java
  src/main/java/com/chatcode/repository/avatar/AvatarReadRepository.java
  src/main/java/com/chatcode/repository/content/ContentWriteRepository.java
  src/main/resources/yaml/application-log.yaml
Labels: ⭐ Feature

#58 Feature/#57 add avatar content
  db/mysql/initdb.d/create_table.sql
  src/main/java/com/chatcode/domain/entity/Avatar.java
  src/main/java/com/chatcode/dto/avatar/AvatarRequest.java
  src/main/java/com/chatcode/dto/avatar/AvatarResponse.java
  src/main/java/com/chatcode/service/AvatarService.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/Avatar.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/pojos/Avatar.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/records/AvatarRecord.java
Labels: ⭐ Feature

#45 Feature/#42 article tag
  db/mysql/initdb.d/create_table.sql
  src/main/java/com/chatcode/controller/ArticleController.java
  src/main/java/com/chatcode/domain/entity/ArticleTag.java
  src/main/java/com/chatcode/domain/entity/Tag.java
  src/main/java/com/chatcode/dto/article/ArticleRequestDTO.java
  src/main/java/com/chatcode/repository/article/ArticleRepository.java
  src/main/java/com/chatcode/repository/article/ArticleTagRepository.java
  src/main/java/com/chatcode/repository/article/TagRepository.java
  src/main/java/com/chatcode/service/ArticleService.java
  src/main/java/com/chatcode/service/ArticleTagService.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/Tag.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/pojos/Tag.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/records/TagRecord.java
Labels: ⭐ Feature

#61 feat(interestTag): POST(/avatars/interest-tags) 기능 요구 사항 변경
  src/main/java/com/chatcode/controller/InterestTagController.java
  src/main/java/com/chatcode/domain/entity/Avatar.java
  src/main/java/com/chatcode/service/AvatarService.java
Labels: ⭐ Feature
