Repository ChatCode9/ChatCode-backend, pull requests merged in 2024-05, with the labels that each got.

#12 [PR] Feature/#4: oauth2-jwt
  build.gradle
  db/mysql/initdb.d/create_table.sql
  db/mysql/initdb.d/insert_roles.sql
  src/main/java/com/chatcode/config/SecurityConfig.java
  src/main/java/com/chatcode/config/auth/LoginUser.java
  src/main/java/com/chatcode/config/auth/jwt/ExternalProperties.java
  src/main/java/com/chatcode/config/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/chatcode/config/auth/jwt/JwtExceptionFilter.java
  src/main/java/com/chatcode/config/auth/jwt/JwtProvider.java
  src/main/java/com/chatcode/config/auth/oauth/LoginOauth2UserService.java
  src/main/java/com/chatcode/config/auth/oauth/OAuth2SuccessHandler.java
  src/main/java/com/chatcode/config/auth/oauth/OAuth2UserInfo.java
  src/main/java/com/chatcode/config/auth/oauth/dto/UserDto.java
  src/main/java/com/chatcode/controller/UserController.java
  src/main/java/com/chatcode/repository/UserRepository.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/Keys.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/Avatar.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/LoggedIn.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/Oauthid.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/Role.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/User.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/pojos/User.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/records/UserRecord.java
  src/main/resources/application.yaml
  src/test/java/com/chatcode/config/SecurityConfigTest.java
  src/test/java/com/chatcode/config/auth/jwt/JwtAuthenticationFilterTest.java
  src/test/java/com/chatcode/config/auth/jwt/JwtProviderTest.java
Labels: ⭐ Feature

#14 Feature/#7 like dislike
  build.gradle
  db/.env
  db/docker-compose.yml
  src/main/java/com/chatcode/config/JooqConfig.java
  src/main/java/com/chatcode/config/RedisConfig.java
  src/main/java/com/chatcode/controller/ArticleController.java
  src/main/java/com/chatcode/controller/LikeController.java
  src/main/java/com/chatcode/domain/LikeableContentType.java
  src/main/java/com/chatcode/domain/entity/Article.java
  src/main/java/com/chatcode/domain/entity/Opinion.java
  src/main/java/com/chatcode/dto/like/LikeRequest.java
  src/main/java/com/chatcode/dto/like/Likeable.java
  src/main/java/com/chatcode/dto/like/ReactionType.java
  src/main/java/com/chatcode/exception/common/ResourceNotFoundException.java
  src/main/java/com/chatcode/exception/reaction/AlreadyReactException.java
  src/main/java/com/chatcode/repository/ReadRepository.java
  src/main/java/com/chatcode/repository/RedisReactionRepository.java
  src/main/java/com/chatcode/repository/WriteRepository.java
  src/main/java/com/chatcode/repository/article/ArticleReadRepository.java
  src/main/java/com/chatcode/repository/article/ArticleWriteRepository.java
  src/main/java/com/chatcode/repository/opinion/OpinionReadRepository.java
  src/main/java/com/chatcode/repository/opinion/OpinionWriteRepository.java
  src/main/java/com/chatcode/service/JooqArticleService.java
  src/main/java/com/chatcode/service/LikeService.java
  src/main/java/com/chatcode/table.sql
  src/main/resources/application.yaml
  src/test/java/com/chatcode/controller/ArticleControllerTest.java
Labels: ⭐ Feature

#21 Docs
  build.gradle
  src/main/java/com/chatcode/config/SwaggerConfig.java
  src/main/java/com/chatcode/controller/example/README.md
  src/main/java/com/chatcode/controller/example/TestController.java
  src/main/java/com/chatcode/controller/example/dto/PostRequestDTO.java
  src/main/java/com/chatcode/controller/example/dto/PostResponseDTO.java
Labels: 🌏 Environment

#20 [PR] Feature/#4 oauth2 jwt
  build.gradle
  db/mysql/initdb.d/create_table.sql
  src/main/java/com/chatcode/ChatcodeApplication.java
  src/main/java/com/chatcode/config/SecurityConfig.java
  src/main/java/com/chatcode/config/auth/LoginUser.java
  src/main/java/com/chatcode/config/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/chatcode/config/auth/jwt/JwtExceptionFilter.java
  src/main/java/com/chatcode/config/auth/jwt/JwtProvider.java
  src/main/java/com/chatcode/config/auth/jwt/JwtSettings.java
  src/main/java/com/chatcode/config/auth/oauth/OAuth2LoginUserService.java
  src/main/java/com/chatcode/config/auth/oauth/OAuth2SuccessHandler.java
  src/main/java/com/chatcode/config/auth/oauth/dto/OAuth2Response.java
  src/main/java/com/chatcode/config/auth/oauth/dto/UserDto.java
  src/main/java/com/chatcode/domain/RoleType.java
  src/main/java/com/chatcode/domain/entity/Role.java
  src/main/java/com/chatcode/domain/entity/User.java
  src/main/java/com/chatcode/repository/role/RoleReadRepository.java
  src/main/java/com/chatcode/repository/role/RoleWriteRepository.java
  src/main/java/com/chatcode/repository/user/UserReadRepository.java
  src/main/java/com/chatcode/repository/user/UserWriteRepository.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/Keys.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/Avatar.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/LoggedIn.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/Oauthid.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/Role.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/User.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/pojos/User.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/records/UserRecord.java
  src/main/resources/application.yaml
  src/test/java/com/chatcode/config/SecurityConfigTest.java
  src/test/java/com/chatcode/config/auth/jwt/JwtAuthenticationFilterTest.java
  src/test/java/com/chatcode/config/auth/jwt/JwtProviderTest.java
Labels: ⭐ Feature

#22 Feature/#16 board crud
  .gitignore
  build.gradle
  db/.env
  db/mysql/initdb.d/create_table.sql
  src/main/java/com/chatcode/controller/ArticleController.java
  src/main/java/com/chatcode/dto/ArticleRequestDTO.java
  src/main/java/com/chatcode/dto/ArticleResponseDTO.java
  src/main/java/com/chatcode/exception/common/ContentNotFoundException.java
  src/main/java/com/chatcode/repository/ArticleRepository.java
  src/main/java/com/chatcode/service/ArticleService.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/Article.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/Content.java
Labels: ⭐ Feature

#25 [PR] chore: 설정 변경 사항들
  .gitignore
  src/main/java/com/chatcode/domain/AuditingFields.java
  src/main/java/com/chatcode/domain/entity/Role.java
  src/main/java/com/chatcode/domain/entity/User.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
  src/main/resources/yaml/application-jwt.yaml
  src/main/resources/yaml/application-log.yaml
Labels: 🌏 Environment, 🛠️ Refactor

#31 Feature/#28 file upload
  .gitignore
  build.gradle
  db/mysql/initdb.d/create_table.sql
  src/main/java/com/chatcode/config/SwaggerConfig.java
  src/main/java/com/chatcode/controller/ArticleController.java
  src/main/java/com/chatcode/controller/FileController.java
  src/main/java/com/chatcode/domain/entity/File.java
  src/main/java/com/chatcode/domain/file/ImageFile.java
  src/main/java/com/chatcode/dto/file/FileDto.java
  src/main/java/com/chatcode/dto/file/FileRequestDto.java
  src/main/java/com/chatcode/dto/file/FileResponseDto.java
  src/main/java/com/chatcode/exception/GlobalExceptionHandler.java
  src/main/java/com/chatcode/exception/file/EmptyImageFileException.java
  src/main/java/com/chatcode/exception/file/ImageFileUploadException.java
  src/main/java/com/chatcode/repository/file/FileRepository.java
  src/main/java/com/chatcode/service/FileService.java
  src/main/java/com/chatcode/service/S3Service.java
  src/main/resources/application.yaml
Labels: ⭐ Feature

#34 Feature/#13 avatar
  db/mysql/initdb.d/create_table.sql
  src/main/java/com/chatcode/config/auth/LoginUser.java
  src/main/java/com/chatcode/config/auth/oauth/OAuth2LoginUserService.java
  src/main/java/com/chatcode/controller/AvatarController.java
  src/main/java/com/chatcode/domain/entity/Avatar.java
  src/main/java/com/chatcode/domain/entity/User.java
  src/main/java/com/chatcode/dto/avatar/AvatarRequest.java
  src/main/java/com/chatcode/dto/avatar/AvatarResponse.java
  src/main/java/com/chatcode/repository/avatar/AvatarReadRepository.java
  src/main/java/com/chatcode/repository/avatar/AvatarWriteRepository.java
  src/main/java/com/chatcode/repository/user/UserReadRepository.java
  src/main/java/com/chatcode/service/AvatarService.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/Avatar.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/pojos/Avatar.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/records/AvatarRecord.java
Labels: ⭐ Feature

#27 Feature/#24 category
  build.gradle
  db/mysql/initdb.d/create_table.sql
  src/main/java/com/chatcode/config/SwaggerConfig.java
  src/main/java/com/chatcode/controller/CategoryController.java
  src/main/java/com/chatcode/domain/entity/Category.java
  src/main/java/com/chatcode/dto/category/CategoryRequest.java
  src/main/java/com/chatcode/dto/category/CategoryResponse.java
  src/main/java/com/chatcode/exception/GlobalExceptionHandler.java
  src/main/java/com/chatcode/exception/category/IllegalCategoryOrderException.java
  src/main/java/com/chatcode/repository/category/CategoryReadRepository.java
  src/main/java/com/chatcode/repository/category/CategoryWriteRepository.java
  src/main/java/com/chatcode/service/CategoryService.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/Keys.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/Category.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/pojos/Category.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/records/CategoryRecord.java
  src/main/resources/db/teardown.sql
  src/test/java/com/chatcode/controller/CategoryControllerTest.java
  src/test/java/com/chatcode/repository/category/CategoryReadRepositoryTest.java
  src/test/java/com/chatcode/service/CategoryServiceTest.java
Labels: ⭐ Feature

#39 파일 업로드 안되는 이슈 트러블 슈팅
  src/main/java/com/chatcode/config/WebConfig.java
  src/main/java/com/chatcode/controller/FileController.java
  src/main/java/com/chatcode/domain/file/Base64ToMultipartFileConverter.java
  src/main/java/com/chatcode/domain/file/DataUrl.java
  src/main/java/com/chatcode/domain/file/ImageFile.java
  src/main/java/com/chatcode/dto/file/FileRequestDto.java
  src/main/java/com/chatcode/service/FileService.java
Labels: 🐞 Bug, 🛠️ Refactor

#38 Feature/#30 Scrap
  src/main/java/com/chatcode/controller/ScrapController.java
  src/main/java/com/chatcode/domain/entity/Article.java
  src/main/java/com/chatcode/domain/entity/Scrap.java
  src/main/java/com/chatcode/dto/ScrapResponseDTO.java
  src/main/java/com/chatcode/repository/scrap/ScrapReadRepository.java
  src/main/java/com/chatcode/repository/scrap/ScrapWriteRepository.java
  src/main/java/com/chatcode/service/ScrapService.java
Labels: ⭐ Feature

#40 Feature/#35 follow
  src/main/java/com/chatcode/controller/FollowController.java
  src/main/java/com/chatcode/domain/entity/Follow.java
  src/main/java/com/chatcode/dto/avatar/AvatarResponse.java
  src/main/java/com/chatcode/repository/follow/FollowReadRepository.java
  src/main/java/com/chatcode/repository/follow/FollowWriteRepository.java
  src/main/java/com/chatcode/service/FollowService.java
  src/main/resources/application-dev.yaml
  src/main/resources/db/teardown.sql
  src/test/java/com/chatcode/repository/follow/FollowReadRepositoryTest.java
Labels: ⭐ Feature
