Repository ChatCode9/ChatCode-backend, pull requests merged in 2024-07, with the labels that each got.

#62 feat(error code): error code 등록 및 custom exception 리펙토링
  src/main/java/com/chatcode/exception/ExceptionCode.java
  src/main/java/com/chatcode/exception/GlobalExceptionHandler.java
  src/main/java/com/chatcode/exception/category/CategoryException.java
  src/main/java/com/chatcode/exception/category/CategoryOrderException.java
  src/main/java/com/chatcode/exception/category/IllegalCategoryOrderException.java
  src/main/java/com/chatcode/exception/common/ContentNotFoundException.java
  src/main/java/com/chatcode/exception/common/NotFoundException.java
  src/main/java/com/chatcode/exception/common/ResourceNotFoundException.java
  src/main/java/com/chatcode/exception/file/EmptyImageFileException.java
  src/main/java/com/chatcode/exception/file/ImageException.java
  src/main/java/com/chatcode/exception/file/ImageFileUploadException.java
  src/main/java/com/chatcode/exception/reaction/AlreadyReactException.java
  src/main/java/com/chatcode/exception/reaction/ReactException.java
  src/main/java/com/chatcode/repository/article/ArticleRepository.java
  src/main/java/com/chatcode/service/ArticleService.java
  src/main/java/com/chatcode/service/AvatarService.java
  src/main/java/com/chatcode/service/CategoryService.java
  src/main/java/com/chatcode/service/FollowService.java
  src/main/java/com/chatcode/service/InterestTagService.java
  src/main/java/com/chatcode/service/LikeService.java
  src/main/java/com/chatcode/service/ScrapService.java
Labels: ⭐ Feature, 🛠️ Refactor

#63 feat: article find by Id API 최신화
  src/main/java/com/chatcode/controller/ArticleController.java
  src/main/java/com/chatcode/dto/article/ArticleDetailResponseDto.java
  src/main/java/com/chatcode/exception/GlobalExceptionHandler.java
  src/main/java/com/chatcode/repository/article/ArticleReadRepository.java
  src/main/java/com/chatcode/repository/article/ArticleRepository.java
  src/main/java/com/chatcode/service/ArticleService.java
  src/main/java/com/chatcode/service/LikeService.java
Labels: ⭐ Feature

#64 Docs(api): swagger api 명세서 보완
  src/main/java/com/chatcode/config/SwaggerConfig.java
  src/main/java/com/chatcode/controller/ArticleController.java
  src/main/java/com/chatcode/controller/AvatarController.java
  src/main/java/com/chatcode/controller/CategoryController.java
  src/main/java/com/chatcode/controller/FileController.java
  src/main/java/com/chatcode/controller/FollowController.java
  src/main/java/com/chatcode/controller/InterestTagController.java
  src/main/java/com/chatcode/controller/ScrapController.java
  src/main/java/com/chatcode/service/ArticleService.java
Labels: 📄 Docs

#59 Feature/#35 valid dto checking
  .github/workflows/cr.yml
  src/main/java/com/chatcode/controller/ArticleController.java
  src/main/java/com/chatcode/controller/AvatarController.java
  src/main/java/com/chatcode/controller/CategoryController.java
  src/main/java/com/chatcode/controller/FollowController.java
  src/main/java/com/chatcode/controller/InterestTagController.java
  src/main/java/com/chatcode/controller/ScrapController.java
  src/main/java/com/chatcode/domain/file/DataUrl.java
  src/main/java/com/chatcode/dto/article/ArticleDetailResponseDto.java
  src/main/java/com/chatcode/dto/article/ArticleRequestDTO.java
  src/main/java/com/chatcode/dto/avatar/AvatarRequest.java
  src/main/java/com/chatcode/dto/category/CategoryRequest.java
  src/main/java/com/chatcode/dto/tag/InterestTagRequest.java
  src/main/java/com/chatcode/handler/aop/DtoValidationAdvice.java
  src/main/java/com/chatcode/handler/exception/ExceptionCode.java
  src/main/java/com/chatcode/handler/exception/GlobalExceptionHandler.java
  src/main/java/com/chatcode/handler/exception/category/CategoryException.java
  src/main/java/com/chatcode/handler/exception/category/CategoryOrderException.java
  src/main/java/com/chatcode/handler/exception/category/IllegalCategoryOrderException.java
  src/main/java/com/chatcode/handler/exception/common/ContentNotFoundException.java
  src/main/java/com/chatcode/handler/exception/common/NotFoundException.java
  src/main/java/com/chatcode/handler/exception/common/ResourceNotFoundException.java
  src/main/java/com/chatcode/handler/exception/dto/DtoValidationException.java
  src/main/java/com/chatcode/handler/exception/file/EmptyImageFileException.java
  src/main/java/com/chatcode/handler/exception/file/ImageException.java
  src/main/java/com/chatcode/handler/exception/file/ImageFileUploadException.java
  src/main/java/com/chatcode/handler/exception/reaction/AlreadyReactException.java
  src/main/java/com/chatcode/handler/exception/reaction/ReactException.java
  src/main/java/com/chatcode/repository/article/ArticleReadRepository.java
  src/main/java/com/chatcode/repository/article/ArticleRepository.java
  src/main/java/com/chatcode/service/ArticleService.java
  src/main/java/com/chatcode/service/AvatarService.java
  src/main/java/com/chatcode/service/CategoryService.java
  src/main/java/com/chatcode/service/FollowService.java
  src/main/java/com/chatcode/service/InterestTagService.java
  src/main/java/com/chatcode/service/LikeService.java
  src/main/java/com/chatcode/service/S3Service.java
  src/main/java/com/chatcode/service/ScrapService.java
  src/test/java/com/chatcode/controller/InterestTagControllerTest.java
  src/test/java/com/chatcode/dto/category/CategoryRequestTest.java
Labels: ⭐ Feature

#69 Feature/#68 article category
  db/mysql/initdb.d/create_table.sql
  src/main/java/com/chatcode/config/dummy/DummyDevInit.java
  src/main/java/com/chatcode/controller/ArticleController.java
  src/main/java/com/chatcode/domain/entity/Article.java
  src/main/java/com/chatcode/domain/entity/Category.java
  src/main/java/com/chatcode/dto/article/ArticleRequestDTO.java
  src/main/java/com/chatcode/handler/exception/ExceptionCode.java
  src/main/java/com/chatcode/repository/article/ArticleReadRepository.java
  src/main/java/com/chatcode/repository/article/ArticleRepository.java
  src/main/java/com/chatcode/repository/category/CategoryReadRepository.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/Article.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/pojos/Article.java
  src/main/java/jooq/chatcode/com/chatcode/jooq/tables/records/ArticleRecord.java
Labels: 🐞 Bug, ⭐ Feature
